### ISSUE TITLE
sniffio was removed from the install_requires, but is still imported in _aio.py

### ISSUE THREAD

**Issue by EmilRinggaard-zoetis** [codypiersall/pynng#119]
When importing pynng, python throws ModuleNotFoundError:

`/home/developer/.local/lib/python3.10/site-packages/pynng/_aio.py:6: in <module>
    import sniffio
E   ModuleNotFoundError: No module named 'sniffio`

The dependency to sniffio was removed in this PR https://github.com/codypiersall/pynng/pull/118/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L194, but sniffio is still imported in:

https://github.com/codypiersall/pynng/blob/55323fe8c921a404b1e691c076c1067baeab98a1/pynng/_aio.py#L6

Current work around is to add sniffio to the requirements.txt file for your project that is using pynng

**Comment by codypiersall** [comment]
Thanks for the catch.  I just pushed something to fix this and I'll have new wheels pushed to PyPI soon.

**Comment by codypiersall** [comment]
Pushed v0.7.4, which has this fix, to PyPI.

**Comment by EmilRinggaard-zoetis** [comment]
Thank you so much for you fast fix, much appreciated :+1:
