### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [codypiersall/pynng#120]
Hi @codypiersall,

thanks very much for your excellent work here! 

We recently faced the issue that `pynng` wasn't available with its newest versions on conda-forge for `osx-arm64`.

Now that support for nng `v1.6.0` is enabled, I was wondering whether you could release a new patch version on `PyPi` with this feature. This would greatly help us in providing a conda-forge version of `pynng` that would work on `osx-arm64` again.

Best,
Thomas

**Comment by codypiersall** [comment]
I'm trying to update the mbedtls dependency, but hopefully I can figure out the build issues with that (works on my computer, but not in CI because the build dependencies get placed in a  different location than `nng` expects). Once I get that working, or once I give up, I'll cut a new release.

Thanks for the interest!

**Comment by ThomasMarwitzQC** [comment]
Ok, best of luck then :) 

Thanks for your work!

**Comment by ThomasMarwitzQC** [comment]
@codypiersall thanks for your work, looks promising!

Could you upload the 2 missing commits of the `v0.8.0` tag to master and upload the sdist on PyPI? Many thanks! I will then look into the `pynng-feedstock` :)

**Comment by codypiersall** [comment]
Yeah, I had hoped to do this yesterday, but my internet went out at home so I was internetless—hoping to do this some evening this week, if my internet starts working again!

**Comment by codypiersall** [comment]
pynng 0.8.0 is now released and on PyPI. It is based on new nng lib version and new MbedTLS version, and thanks to #122, builds universal Mac wheels . If it doesn't work, please re-open this issue!
