### ISSUE TITLE
Support TLS connections

### ISSUE THREAD

**Issue by codypiersall** [codypiersall/pynng#20]
NNG can be built with support for TLS connections using [mbedTLS](https://tls.mbed.org/).  We should support this in one way or another.  I would like the default install of pynng to include the ability to make secure connections.  However, there are a few points to work out:

* I don't *think* that nng supports linking to mbedTLS statically.  Usually this is better anyway, since it's especially nice to be able to upgrade security libraries without rebuilding everything else, but on the other hand it's nice to be *certain* that everything can work with the normal `python setup.py install` incantation.
* If we don't link statically, binary wheels will not work when mbedTLS is not present.

I want to tackle #10 first, because I think that will make developing this easier.

More thinking needs to go into this...

**Comment by kejtan** [comment]
Hi there i was wondering if there are any near future plans on this feature? Thanks!

**Comment by codypiersall** [comment]
Hi @kejtan, Thanks for the interest.

I don't have any plans to work on this in the near term, but I _am_ still interested in doing it at some point.  Maybe over the holidays, if I can find the time.

**Comment by codypiersall** [comment]
The GitHub user xzz53 sent me an email recently telling me about some work he has done for tls support over at https://github.com/xzz53/pynng-tls.  They got it working on Linux, but Mac and Windows may need some work.  I'm tracking my work integrating it into the repository in #52.  This should be landing relatively soon!

**Comment by codypiersall** [comment]
This is now in master, thanks to @xzz53.
