### ISSUE TITLE
Update tests to use asyncio and trio testing decorators

### ISSUE THREAD

**Issue by codypiersall** [codypiersall/pynng#28]
I didn't know these existed until #25.  It would be better to not create an event loop every time we need a new test; we can just mark the tests with [`pytest.mark.asyncio`] for asyncio tests and `trio_test` for trio tests.

**Comment by tgoodlet** [comment]
@codypiersall it might be even better to use the [`pytest` plugin](https://github.com/python-trio/pytest-trio) which comes with a some niceties like [async fixtures](https://pytest-trio.readthedocs.io/en/latest/quickstart.html#async-fixtures) and a special [`pytest.mark.trio`](https://pytest-trio.readthedocs.io/en/latest/reference.html#trio-mode) for handling test sets including other frameworks (i.e. `asyncio`).  

@njsmith [prefers use of the plugin over `@trio_test`](https://gitter.im/python-trio/general?at=5c47ed45ba355012a481effa) so it's my bad for leading with that example. I've got to move to the plugin for my own project as well.

**Comment by codypiersall** [comment]
Thanks for the info!  That's news to me.  I'll switch to using that then.

**Comment by codypiersall** [comment]
Got the first part of the way there in 37c3c7c1f810be845c3b226f1f2df11773b1cbff.

**Comment by codypiersall** [comment]
Thanks for pointing this out @tgoodlet!  It's fixed now in 048df6ffc82f9f9836ee167957bd4e864c19d8e3.
