### ISSUE TITLE
avoid sleep() calls in documentation examples

### ISSUE THREAD

**Issue by parity3** [codypiersall/pynng#34]
I'm pretty sure this is only an issue for sync versions but I'm seeing many cases that seem to point to entered contexts not having waited for the objects to be fully "ready" due to start()ing threads without waiting on any "I'm ready" event from the thread. Example:

```
with Bus0(listen=address, recv_timeout=100) as s0, \
        Bus0(dial=address, recv_timeout=100) as s1, \
        Bus0(dial=address, recv_timeout=100) as s2:
    # let all connections be established
    time.sleep(0.05)
```

If that is truly unavoidable or inefficient it may be advisable to give a more explicit warning for all sync calls in the documentation, or to provide a helper in the library to wait_ready(s0, s1, s2) that abstracts away the ugly sleeps (and maybe use something more reliable like an assertion at the end to make sure the wait was long enough, or a cycle with timeout, etc)

**Comment by codypiersall** [comment]
First off, thanks for opening an issue!  The `sleep` calls are something that kind of bother me too.  In fact, in the tests that I've written I have a [helper function](https://github.com/codypiersall/pynng/blob/83a5516f9c742b1ea3eb15d2d1f5bcc937d6e237/test/_test_util.py#L4) that waits for connections to be established.  There's still a sleep in that function, but that's not _strictly_ necessary.

The sleep is, I think, pretty appropriate for the examples.  I want to keep them short.  If someone needs to make sure that sockets are connected to each other before they continue in the code, they will have to either poll the length of `Socket.pipes` until the length is the right value, or register a callback using `Socket.add_pre_pipe_connect_cb` or `Socket.add_post_pipe_connect_cb` to set a flag that can be checked or something.

Maybe the docs could grow a "Recipes" section that shows a better alternative to calling `sleep` for waiting for the connection to be established.  For most of my applications, a sleep at the beginning of the program is not a big deal at all, but I would believe there are use cases where it's a problem.

I'm not sure what you mean by sync calls though, could you clarify that?  There's not an asynchronous version of dial or listen, even though nng actually implements them asynchronously under the hood.

**Comment by parity3** [comment]
re: sync calls, I just assumed that if there were threads involved that there would be an async version without threads that just awaited?

I'm glad there's already a callback mechanism.. looks like there's a clear mechanism to avoid the sleep with add_post_pipe_connect_to. That would be the first thing I'd do :)
