### ISSUE TITLE
Cannot integrate with nng

### ISSUE THREAD

**Issue by JimmyZhangJW** [codypiersall/pynng#38]
Hi, I have a c subscriber program which subscribes to any topic and a python publisher program using pynng. However, my subscriber program cannot receive anything from the python program.

**Comment by codypiersall** [comment]
Thanks for opening up an issue.

Could you give some example code that shows this happening?  Communication between C programs using nanomsg or nng should work, so any reproducing code you can provide will help figure out what's going on.

**Comment by codypiersall** [comment]
Since there hasn't been any motion on this, I'm going to close it.  If this is still a problem for you, feel free to reopen with some more details.
