### ISSUE TITLE
Support nng_aio

### ISSUE THREAD

**Issue by codypiersall** [codypiersall/pynng#4]
We need an interface for nng_aio.  Initially I'd like to just support registering Python callbacks, but eventually it would be nice to be able to operate with Python event loops like [trio](https://github.com/python-trio/trio).

The tricky bit will be enabling registering Python functions, since naturally nng registers C functions.

**Comment by codypiersall** [comment]
@tgoodlet Thanks for the links!  I've looked at them a bit now, but hopefully I'll be able to really dive in to them in the next couple days.  It's election day for midterms in the US, and I had procrastinated doing my research on candidates to vote for until this evening.

It does seem that this will be less straightforward than I had hoped; alas, that is life.

**Comment by tgoodlet** [comment]
@codypiersall no prob! And yes the midterms are very important (especially these days it seems) so :+1: 

I was hoping to dive into a `trzmq` solution before finding `nng` and then seeing you had already started on a wrapper. If you need help with `trio` internals I'm glad to help with what I know and of course the community [gitter channel](https://gitter.im/python-trio/general) is fantastic.

Talk soon!

**Comment by gdamore** [comment]
This is interesting.  If there is feedback as to changes that we can make in NNG itself to make this kind of work easier, please let me know.  I don't work with Python regularly, but I'm interested in ensuring that there are as few barriers as possible in NNG itself.

**Comment by jiangrzh** [comment]
marked! 😄 
👍

**Comment by njsmith** [comment]
@gdamore Oh hey, one of the worst things about zmq is how hostile it is to interoperating with foreign event loops, so if avoiding that is on your radar then that makes nng even more interesting :-).

@codypiersall I'm also happy to help figure out how to get things working with trio :-)

You're using cffi, right? cffi actually makes it pretty straightforward to convert a Python function to a C function pointer: https://cffi.readthedocs.io/en/latest/using.html#extern-python-new-style-callbacks

It's definitely possible to wrap a low-level API that uses callbacks into a more native-feeling Trio API. Users would write `await some_operation()`, where that's a wrapper that uses the lower-level APIs to start `some_operation` running, register a callback, and then suspends the calling task; and then when operation finishes, the callback runs, it reschedules the task, and the async function call returns. So from the user's perspective, it's just like a function call, even if it uses complicated callback stuff underneath.

The big question is how nng integrates into the core I/O loop. From a quick skim of the documentation, I'm having trouble understanding how the library works in the big picture (what's the relationship between sockets/dialers/listeners/pipes/protocols?), but from my understanding of the aio stuff, it basically shunts all the actual I/O handling off into separate threads that nng manages, and then it issues callbacks (and I assume these callbacks may execute in random other threads). That should be very easy to integrate into Trio -- you just let nng do its thing in whatever threads it's using, and then when your callback wants to get back into the Trio thread to resume a task, then we have a [standard way to do that](https://trio.readthedocs.io/en/latest/reference-hazmat.html#trio-tokens).

**Comment by codypiersall** [comment]
I think I have a plan that should work, but I could be wrong on my understanding of how the pieces fit together.  Here is my idea:

0. First, just to clarify, nng doesn't really _have_ an event loop, so I don't think there's anything to fight with there.  nng does not want to take over a process; it provides an abstraction for asynchronous operations.  The `nng_aio*` functions are loosely based on [Posix aio functions](http://man7.org/linux/man-pages/man7/aio.7.html), but with convenient ways of making callbacks happen.  We can use these callbacks to integrate with event loops, I think.
1. The goal is to have a method that users can call like this, and it will integrate with an event loop:
        
       s = Pair0(dial='tcp://127.0.0.1:9001')
       bytes = await s.arecv()  # asynchronous

2. To that end (this is where I could be going wrong), we can implement a solution where `Socket.arecv()` which:
    1. Creates a `Future` object with `loop = asyncio.get_running_loop(); future = loop.create_future()`
    2. Calls `nng_aio_alloc()` with the created `future` as the `callb` parameter. (I need to understand how nng's aio operations work better; I may need to pass a struct that has a pointer to the allocated aio, and the Future)
    3. The callback would call `future.set_result()`, which would be either the bytes or an Exception.   This should be event loop agnostic, so should work with trio or any other loop.

If my understanding of how all these things work together is correct, this approach should work.  I know that CPython stores a lot of thread-local variables, e.g. [PEP 567](https://www.python.org/dev/peps/pep-0567/#asyncio), so if messing with Python objects in threads that Python isn't aware exists is a problem there will have to be another indirection, but that's a solvable problem; we could just start a thread when the library is imported ("imports shouldn't have side effects", I know) and use a queue to do the processing in the thread Python knows about.

Some of the details may be off, but I think we have all the pieces we need to make it work.  I'd like to avoid event-loop-specific code, but supporting trio is a priority if push comes to shove.

I think I'll hold off on callback-style asyncio for now, and focus on async-await.

**Comment by codypiersall** [comment]
Initial support is added in the branch [arecv](https://github.com/codypiersall/pynng/tree/arecv).  Currently only support for asyncio exists.  I _do_ want to support trio, but I don't really want to make trio a dependency.  If I don't make trio a dependency, I need to do some stuff at runtime to make sure things will still work. 

At any rate, arecv is working with asyncio, and trio is next!

**Comment by tgoodlet** [comment]
@codypiersall I forgot to mention [`anyio`](https://github.com/agronholm/anyio) could be worth looking at if you want to support `curio` and `trio` as well without custom adapters.

I might take a look at your `asyncio` solution and see I can drum up the `trio` end if you don't mind :)

**Comment by codypiersall** [comment]
@tgoodlet Please, feel free!  I'm working on it as I can, but man I'm slow, and you very well may beat me.

I assumed (incorrectly) that Python would have some sort of an abstract interface that I could implement and then `arecv()` would work across event loop implementations — silly me! The anyio library looks like in concept it's exactly what I want.  I don't want to be tied to an event loop, because I'd like to be as general purpose as possible.  At the same time I don't want to implement the coordination of every async library under the sun.

I haven't ever actually done any asynchronous programming before, so on the one hand this is an exciting little adventure; on the other hand, I may be doing and saying some pretty dumb things.

Thanks to everyone for helping out with info so far.  @njsmith reminding about cffi Python callbacks was spot on, and the links for trio was way better than trying to find the right page myself, @gdamore clarifying how the aios can be used saved me plenty of time, and @tgoodlet thanks for giving lots of good pointers.  I'm progressing slower than I'd like, but I want to make sure I get this right.  

Supporting a nice API for aios is essential for supporting nng contexts, which is one of the really big wins of nng over nanomsg, in my opinion.

**Comment by njsmith** [comment]
`anyio` picks a certain level of abstraction to work at, and tries to provide a rich set of tools like timeouts, networking, task spawning, etc. But since nng's AIO abstraction takes care of so much for you, I don't think you actually care about all that stuff... you just need the ability to suspend a task, resume it from a cross-thread callback, and handle cancellation. I don't think anyio provides these? I could be wrong.

For Trio, this is done with [`wait_task_reschedule`](https://trio.readthedocs.io/en/latest/reference-hazmat.html#low-level-blocking) for the suspend/resume/cancellation, and a [`TrioToken`](https://trio.readthedocs.io/en/latest/reference-hazmat.html#trio-tokens) for the cross-thread part. Since these were designed to work well with Windows AIO, and since nng AIO is inspired directly by Windows AIO, this is actually reasonably straightforward. I guess your `arecv` would look something like:

```python
def _async_complete(void_p):
    id = int(ffi.cast('size_t', void_p))
    resumer = _aio_map.pop(id)
    resumer()

class Socket:
    async def arecv(self):
        # Record the info needed to get back into this task
        token = trio.hazmat.current_trio_token()
        task = trio.hazmat.current_task()
        def resumer():
            token.run_sync_soon(trio.hazmat.reschedule, task)
        _aio_map[id(arg)] = resumer
        idarg = id(arg)
        as_void = ffi.cast('void *', idarg)

        # Create the nng aio object and start the operation
        aio_p = ffi.new('nng_aio **')
        lib.nng_aio_alloc(aio_p, lib._async_complete, as_void)
        try:
            aio = aio_p[0]
            lib.nng_recv_aio(self.socket, aio)

            # Machinery to handle Trio cancellation, and convert it into nng cancellation
            raise_cancel_fn = None
            def abort_fn(raise_cancel_arg):
                # This function is called if Trio wants to cancel the operation.
                # First, ask nng to cancel the operation.
                lib.nng_aio_cancel(aio)
                # nng cancellation doesn't happen immediately, so we need to save the raise_cancel function
                # into the enclosing scope to call it later, after we find out if the cancellation actually happened.
                nonlocal raise_cancel_fn
                raise_cancel_fn = raise_cancel_arg
                # And then tell Trio that we weren't able to cancel the operation immediately, so it should keep
                # waiting.
                return trio.hazmat.Abort.FAILED

            # Put the Trio task to sleep.
            await trio.hazmat.wait_task_rescheduled(abort_fn)

            err = lib.nng_aio_result(aio)
            if err == lib.NNG_CANCELED:
                    # This operation was successfully cancelled.
                    # Call the function Trio gave us, which raises the proper Trio cancellation exception
                    raise_cancel_fn()
            check_err(err)
            msg = lib.nng_aio_get_msg(aio)
            try:
                size = lib.nng_msg_len(msg)
                data = ffi.cast('char *', lib.nng_msg_body(msg))
                return bytes(ffi.buffer(data[0:size]))
            finally:
                lib.nng_msg_free(msg)
        finally:
            lib.nng_aio_free(aio)
```

Of course a lot of this code would be the same for all your different async operations, so you might factor it out:

```python
# Context manager to create an AIO handle that will resume the current task on completion
@contextmanager
def aio_handle():
    # Record the info needed to get back into this task
    token = trio.hazmat.current_trio_token()
    task = trio.hazmat.current_task()
    def resumer():
        token.run_sync_soon(trio.hazmat.reschedule, task)
    _aio_map[id(arg)] = resumer
    idarg = id(arg)
    as_void = ffi.cast('void *', idarg)

    # Create the nng aio object
    aio_p = ffi.new('nng_aio **')
    lib.nng_aio_alloc(aio_p, lib._async_complete, as_void)
    try:
        yield aio_p[0]
    finally:
        lib.nng_aio_free(aio)

async def wait_for_aio(aio):
        # Machinery to handle Trio cancellation, and convert it into nng cancellation
        raise_cancel_fn = None
        def abort_fn(raise_cancel_arg):
            # This function is called if Trio wants to cancel the operation.
            # First, ask nng to cancel the operation.
            lib.nng_aio_cancel(aio)
            # nng cancellation doesn't happen immediately, so we need to save the raise_cancel function
            # into the enclosing scope to call it later, after we find out if the cancellation actually happened.
            nonlocal raise_cancel_fn
            raise_cancel_fn = raise_cancel_arg
            # And then tell Trio that we weren't able to cancel the operation immediately, so it should keep
            # waiting.
            return trio.hazmat.Abort.FAILED

        # Put the Trio task to sleep.
        await trio.hazmat.wait_task_rescheduled(abort_fn)

        err = lib.nng_aio_result(aio)
        if err == lib.NNG_CANCELED:
                # This operation was successfully cancelled.
                # Call the function Trio gave us, which raises the proper Trio cancellation exception
                raise_cancel_fn()
        check_err(err)

class Socket:
    async def arecv(self):
        with aio_handle() as aio:
            lib.nng_recv_aio(self.socket, aio)
            await wait_for_aio(aio)
            msg = lib.nng_aio_get_msg(aio)
            try:
                size = lib.nng_msg_len(msg)
                data = ffi.cast('char *', lib.nng_msg_body(msg))
                return bytes(ffi.buffer(data[0:size]))
            finally:
                lib.nng_msg_free(msg)
```

You could potentially reimplement these `aio_handle` and `wait_for_aio` helpers for the different event loops you want to support. I tweaked `_async_complete` so that it can work for multiple event loops without modification :-).

One approach would be to have an `AsyncSocket` class that lets you select which backend to use (or uses [`sniffio`](https://github.com/python-trio/sniffio) to guess), and then instantiates either an `AsyncHelper` or `TrioHelper` object, and these objects have `aio_handle` and `wait_for_aio` as methods. Then `AsyncSocket`'s `recv` would call `self._helper.aio_handle()`, and the actual code could be the same.

You might also want to avoid the combinatorial explosion of `Bus0`/`AsyncBus0`/`Pair0`/`AsyncPair0`/... objects, which I guess is an argument for making the API more like `Socket(mode="bus0")`/`AsyncSocket(mode="bus0", backend="trio")`?

Unfortunately, handling cancellation correctly with asyncio is pretty non-trivial. With a regular `asyncio.Future`, when you do `await fut`, and then your task is cancelled, then the `fut` object immediately becomes cancelled. There's no way to resume waiting on it to find out when the task actually finished. So you need to do something more complicated. Maybe involving a custom `Future`-like class so you can override `cancel`? Or multiple `Future` objects and somehow switching around which one your callback resolves?

**Comment by codypiersall** [comment]
@njsmith that code is immensely helpful.  Thank you!  And as far as I can tell you're right about anyio; I couldn't find their docs ([embarrassingly](https://github.com/agronholm/anyio/issues/35#issuecomment-440501071)), so I went spelunking through the source, and yeah, nothing that would actually help with this.

I'll hopefully have some time before next week to get this into master; it's a holiday week in the U. S. so hopefully I'll be able to get some extra time for this!

**Comment by njsmith** [comment]
After sleeping on it, I realized there is a tricky way to make asyncio work that doesn't require anything as heavyweight as creating your own `Future` class... something like:

```python
async def wait_for_aio(aio):
    already_called_nng_aio_cancel = False
    while True:
        try:
            # fut is set up as in the original branch
            # shield() is a strange function: if our task is cancelled while we're waiting on
            # this future, then shield() still raises CancelledError immediately... but the underlying
            # future *isn't* cancelled, so we can wait on it again later.
            await asyncio.shield(fut)
        except asyncio.CancelledError:
            if not already_called_nng_aio_cancel:
                lib.nng_aio_cancel(aio)
                already_called_nng_aio_cancel = True
            # loop back around to wait again
        else:
            break

        err = lib.nng_aio_result(aio)
        if err == lib.NNG_CANCELED:
            raise asyncio.CancelledError
        check_err(err)
```

**Comment by njsmith** [comment]
Anyway, hopes that help, and like @tgoodlet said, feel free to drop by [our chat channel](https://gitter.im/python-trio/general), we obviously focus on trio but can sometimes help with things like asyncio and anyio too :-)

**Comment by codypiersall** [comment]
Support for arecv was added in https://github.com/codypiersall/pynng/commit/ec99bda32f753f4883a0360d53038990d3fe1f86.

asend is next.  Should be _really_ straightforward.

Thanks for everyone's help!

**Comment by njsmith** [comment]
Awesome!

Don't forget to add [`Framework :: AsyncIO`](https://pypi.org/search/?c=Framework+%3A%3A+AsyncIO) and [`Framework :: Trio`](https://pypi.org/search/?c=Framework+%3A%3A+Trio) tags to your `setup.py` so people can find it :-)

**Comment by Eirikur** [comment]
Egad. I was really hoping that the story my friend told me about simple asyncrony in NNG would be achievable in Python. I'd really rather not deal with asyncio or trio or..... I'd like to use the _aio_ functions with callbacks just as I would in C. Is there some reason this isn't available in pynng? Perhaps I should look into Swig? I haven't been there before despite being a serious Pythonist. I'll look into trio and anyio and sniffio, but I do not quite get why I need to go there.

**Comment by codypiersall** [comment]
Hi @Eirikur,

If you'd like, you can reach into `pynng.lib` and `pynng.ffi`, which exposes the nng library over the CFFI interface, and build whatever interface you'd like yourself.  The reason this isn't available in `pynng` is that I saw it as better to support `trio` and `asyncio`, since it's the API I wanted.

If you want to use the aio functions just as you would in C, you can absolutely do that, just by digging in to `pynng.ffi` and `pynng.lib`.  IIRC it turned out to be a little more complicated to just do callbacks, since you have to worry about memory management etc. at that point, but it's been a little while.
