### ISSUE TITLE
examples/pair1_async.py uses deprecated method

### ISSUE THREAD

**Issue by MauiJerry** [codypiersall/pynng#44]
Trying out the pair1_async example after installing Trio (latest = 0.12.0) i got the message ...

> TrioDeprecationWarning: trio.run_sync_in_worker_thread is deprecated since Trio 0.12.0; use trio.to_thread.to_thread_run_sync instead (https://github.com/python-trio/trio/issues/810)

but be aware that deprecated suggestion is wrong, due to trio/to_thread importing the function as run_sync()  so the updated line should be
>        stuff = await trio.to_thread.run_sync(input, cancellable=True)

**Comment by codypiersall** [comment]
Thanks for pointing this out.  This is fixed now in baaee035db5cc8a46b96400e4d9e0f5b58bb8a6.  The example should work on older or newer versions of trio.
