### ISSUE TITLE
Is there some way to uninstall pynng?

### ISSUE THREAD

**Issue by dongdongzzz** [codypiersall/pynng#46]
I just installed it on my MAC. When i execute `python3 -m pip uninstall pynng` and `pip3 uninstall pynng`. They showed that Can't uninstall 'pynng'. No files were found to uninstall.

**Comment by codypiersall** [comment]
Hi @dongdongzzz,  thanks for opening an issue.  How did you install pynng?  I've installed/uninstalled pynng many many times with no issue.  pynng doesn't do anything special compared to any other Python package, so it would work the same as anywhere else.

**Comment by codypiersall** [comment]
I'm going to go ahead and close this.  I don't think pynng does anything special compared to any other setuptools-based Python project.  Maybe you installed it with `python setup.py install`, and pip never knew anything about it?
