### ISSUE TITLE
Is there a way to connect local server?

### ISSUE THREAD

**Issue by AjayViknesh** [codypiersall/pynng#48]
Hi!

I have installed pynng in a local server and I am able to send and receive in the same server.
Is there any way to communicate and send data to another local server connect within the network ?
For example send data from 192.168.1.58 server to 192.168.1.59 server.

I tried but I am getting "pynng.exceptions.AddressInvalid: Address invalid" Error

**Comment by codypiersall** [comment]
Hi @AjayViknesh,

If you're getting the `AddressInvalid` exception, that means you're trying to `listen` on an IP address that the computer doesn't have.  Could you show the example code on both the client and server?  This is likely a case of mixed-up IP addresses.

Also, for what it's worth, when you say connect _local_ server, I think of connecting to a server over localhost; I would call what you're doing connecting to a _remote_ server.  Even if they're located in the same room :-).

**Comment by AjayViknesh** [comment]
Hi @codypiersall 

Yes, exactly I am trying to connect a remote server.

It is working now. My bad, I did the the dial and listen in the reverse way for the client and server.

Thanks for the quick help.
