### ISSUE TITLE
ValueError: The async backend curio is not currently supported.

### ISSUE THREAD

**Issue by logileifs** [codypiersall/pynng#81]
When trying to run the [pubsub example](https://github.com/codypiersall/pynng/blob/master/examples/pubsub.py) I get the following error: 
```
Task Crash: Task(id=6, name='client', state='TERMINATED')
Traceback (most recent call last):
  File "/home/logi/.virtualenvs/nng/lib/python3.7/site-packages/curio/kernel.py", line 737, in kernel_run
    trap = current.send(current._trap_result)
  File "/home/logi/.virtualenvs/nng/lib/python3.7/site-packages/curio/task.py", line 167, in send
    return self._send(value)
  File "/home/logi/.virtualenvs/nng/lib/python3.7/site-packages/curio/task.py", line 171, in _task_runner
    return await coro
  File "pubsub.py", line 35, in client
    msg = await sock.arecv_msg()
  File "/home/logi/.virtualenvs/nng/lib/python3.7/site-packages/pynng/nng.py", line 643, in arecv_msg
    with _aio.AIOHelper(self, self._async_backend) as aio:
  File "/home/logi/.virtualenvs/nng/lib/python3.7/site-packages/pynng/_aio.py", line 150, in __init__
    .format(async_backend)
ValueError: The async backend curio is not currently supported.
```

**Comment by codypiersall** [comment]
Thanks for submitting the issue.

Unfortunately, curio is not supported yet (see #74).  I would love to see it supported but don't have the bandwidth to work on it at the moment; a pull request adding support for curio would definitely be appreciated!

If you can use another event loop (which I realize you may be unable to!) trio and asyncio are both supported.

**Comment by geronimo-iia** [comment]
Hi, we had merge this on  pull request https://github.com/codypiersall/pynng/pull/74
but, i beleive that you should install pynng from master branch to use it (correct me if i'm wrong)

**Comment by codypiersall** [comment]
@geronimo-iia Oh, thank you for the reminder, I *totally* forgot that you wrote some support for this!  I have no idea what I was doing in October.  Funny thing is that I even linked to #74, your PR, when I meant to link to #23

@logileifs can you test this on master?

**Comment by kyeshmz** [comment]
This definently worked on master! It would be great if this was pushed to be able to use in pip!

**Comment by codypiersall** [comment]
I'll leave this issue open as a reminder until I push a new release.

Glad it's working for you and biiiig things to @geronimo-iia  for actually adding the curio support!

**Comment by codypiersall** [comment]
Should work now with the new release!
