### ISSUE TITLE
wheels for Py 3.9

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [codypiersall/pynng#84]
1. source install of pynng on linux for python 3.9  seems to work fine

2. is there any reason not to release wheels for python 3.9?

https://pypi.org/project/pynng/#files

**Comment by codypiersall** [comment]
Thanks for opening an issue!

There's certainly no reason it can't be done. In a perfect world, the only like that needs to change is here:  https://github.com/codypiersall/pynng/blob/master/.github/workflows/cibuildwheel.yml#L30

I can update this at some point.  It seems likely to me that updating that line will also make changes to CI that will cause failures that will need to be debugged, and at the moment I can't go after it myself.

**Comment by Andrei-Pozolotin** [comment]
1. got it, thank you
2. please review #85
